
    <div class="grid adapting-grid-pad">
        <div class="gray_box">
            <?php
            if(count($this->page_content) > 0) {
                foreach ($this->page_content as $page_item):

                    ?>
                    <h2 class="white_box story-title"><?= $page_item->title?></h2>
                    <div class="message_info_box">
                        <a href="<?= $this->url(array(
                            'controller' => 'pages',
                            'action' => 'overview',
                            'id' => null)) ?>">Terug naar overzicht</a>
                    </div>
                    <div class="white_box">
                        <?= $page_item->content ?>
                    </div>
                    <?php
                endforeach;
            }
            else {
                ?>

                <div class="white_box">
                    <h2 class="section-title">Oeps... deze pagina is niet gevonden.</h2>
                </div>

                <?php
            }
            ?>
        </div>
    </div>

