<h2 class="section-title">Pagina aanpassen</h2>
<div class="grid-pad grid">
    <div class="message_info_box">
        <a href="<?=$this->url(array(
            'controller' => 'pages',
            'action' => 'index',
            'id'    => null)) ?>">Terug naar overzicht</a>
    </div>
    <?php if(isset($this->result) && $this->result > 0): ?>
        <div class="message_info2_box">
            <span class="white">De pagina is aangepast</span>
        </div>
    <?php
        endif;
        if(isset($this->result) && $this->result == 0):
    ?>
        <div class="message_warning_box">
            <span class="white">Er is niks aangepast</span>
        </div>
    <?php
        endif;
    ?>
    <div class="col-10">
        <form method="post">
            <label>Titel
                <input type="text" name="page_title" placeholder="Titel" value="<?=$this->title ?>">
            </label>

            <label>Code
                <input type="text" name="page_code" placeholder="Indentifier" value="<?=$this->identifier ?>">
            </label>

            <label>Content
                <textarea class="jqte_editor" name="page_content" placeholder="Pagina HTML"><?=$this->content ?></textarea>
            </label>
            <label>Indexeren
                <select name="show_overview">
                    <option <?= ($this->index == 'ja') ? 'selected="selected"' : '' ?> value="ja">Ja</option>
                    <option <?= ($this->index == 'nee') ? 'selected="selected"' : '' ?>value="nee">Nee</option>
                </select>
            </label>
            <input type="hidden" name="id" value="<?=$this->id ?>">
            <input class="main-btn" type="submit" value="Pagina Aanpassen">
        </form>
    </div>
</div>

<script>
    $('.jqte_editor').jqte();
</script>