<h2 class="section-title">Pagina overzicht</h2>
<div class="message_info_box">
    <a href="<?=$this->url(array( 'controller' => 'admin', 'action' => 'index'), null, true) ?>">Terug naar dashboard</a>
</div>
<div class="message_info2_box">
    <a href="<?=$this->url(array( 'controller' => 'pages', 'action' => 'new'), null, true) ?>">Pagina aanmaken</a>
</div>
<div class="message_info_box">
    <a href="<?=$this->url(array( 'controller' => 'pages', 'action' => 'overview'), null, true) ?>">Pagina overzicht (users)</a>
</div>

<div class="grid adapting-grid-pad">


        <ul class="admin-list">
            <?php
            foreach($this->pages as $page):
                ?>

                <div class="col-1-3">
                    <div class="gray_box admin-content-item" >
                        <h4><?=$page->id?> - <?=$page->code ?></h4>
                        <span class="content-box-status">Geïndexeerd: <span class="blue"><?=$page->show_overview ?></span></span>
                        <a class="main-btn" href="<?=$this->url(array("controller" => "pages", "action" => "edit","id" => $page->id)) ?>">Aanpassen</a>
                        <a class="main-btn warning-btn" href="<?=$this->url(array("controller" => "pages", "action" => "remove","id" => $page->id)) ?>">Verwijderen</a>
                    </div>

                </div>
                <?php
            endforeach;
            ?>
        </ul>

</div>