<h2 class="section-title">Story overzicht (admin)</h2>
<div class="message_info_box">
    <a href="<?=$this->url(array( 'controller' => 'admin', 'action' => 'index'), null, true) ?>">Terug naar dashboard</a>
</div>
<div class="message_info2_box">
    <a href="<?=$this->url(array( 'controller' => 'story', 'action' => 'new'), null, true) ?>">Story aanmaken</a>
</div>
<!--<div class="grid grid-pad">
    <table class="col-16">
        <thead>
        <tr>
            <th class="col-1">ID</th>
            <th class="col-3">Titel</th>
            <th class="col-3">Timestamp</th>
            <th class="col-3"></th>
            <th class="col-3"></th>
        </tr>
        </thead>
        <tbody>
        <?/*
        foreach($this->stories as $story){
            */?>
            <tr>
                <td class="col-1"><?/*=$story['id'] */?></td>
                <td class="col-3"><?/*=$story['title'] */?></td>
                <td class="col-3"><?/*=$story['time_stamp'] */?></td>
                <td class="col-3"><a class="main-btn" href="<?/*=$this->url(array(
                        'action' => 'edit',
                        'id'    => $story['id']
                    ))*/?>">Aanpassen</a></td>
                <td class="col-3"><a class="main-btn" href="<?/*=$this->url(array(
                        'action' => 'remove',
                        'id'    => $story['id']
                    ))*/?>">Verwijderen</a></td>
            </tr>
            <?/*
        }
        */?>
        </tbody>
    </table>
</div>-->
<div class="grid-pad grid">
    <ul class="admin-list">
        <?php
        foreach($this->stories as $story):
            ?>

            <div class="col-1-3">
                <div class="admin-content-item" >
                    <h4><?=$story['id']?> - <?=substr($story['title'], 0, 40) ?></h4>
                    <div><?=$story['time_stamp'] ?></div>
                    <a class="main-btn" href="<?=$this->url(array(
                        'action' => 'edit',
                        'id'    => $story['id']
                    ))?>">Aanpassen</a>
                    <a class="main-btn warning-btn" href="<?=$this->url(array(
                        'action' => 'remove',
                        'id'    => $story['id']
                    ))?>">Verwijderen</a>
                </div>

            </div>
            <?php
        endforeach;
        ?>
    </ul>
</div>
