
    <?php if(!isset($this->story)):?>
        <div class="grid adapting-grid-pad">
            <div class="gray_box">
                <h2 class="white_box section-title">Stories</h2>

                <?php if(count($this->content) > 0):
                    foreach($this->content as $item):
                    ?>
                        <div class="col-16 no-pad">
                            <div class="white_box">
                                <h3><?=$item->title ?></h3>
                                <?=$item->content ?>
                            </div>
                        </div>
                <?php
                    endforeach;
                endif;
                ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="grid adapting-grid-pad">
        <div id="story-collection-list">
            <?php
            if(isset($this->stories) ):
                foreach($this->stories as $story){
                    ?>

                    <article class="col-1-3 ">
                        <div class="gray_box gray_box_spaced overview_list_block">
                            <h4><?=$story['title'] ?></h4>
                            <span class="blue"><?=substr($story['time_stamp'],0, 10) ?></span>
                            <a class="main-btn" href="<?=$this->url(array(
                                'action' => 'index',
                                'id'    =>  $story['id']
                            )) ?>">Bekijken</a>
                        </div>
                    </article>

                    <?php
                }
        ?>
        </div>
        <div class="pagination-container gray_box">
            <div class="left pagination-button">
                <span class="main-btn" id="page_back">terug</span>
            </div>
            <div class="white_box pagination-counter"><span class="blue"><span class="cur-page"></span>/<span class="max-page"></span></span></div>
            <div class="right pagination-button">
                <span class="main-btn" id="page_next">volgende</span>
            </div>
            <script>
                $(document).ready(function(){

                    var max_number_per_page = 9;
                    var pages = 0;
                    var cur_page = 0;
                    var story_list = $('#story-collection-list');
                    var child_elements = story_list.children();
                    var cur_page_counter = $('.pagination-counter .cur-page');
                    var max_page_counter = $('.pagination-counter .max-page');
                    var number_of_child_elements = child_elements.size();
                    pages = Math.ceil(number_of_child_elements / max_number_per_page);

                    var back_button = $('#page_back');
                    var next_button = $('#page_next');

                    var screen_width = $(window).width();

                    if(screen_width < 580)
                    {
                        back_button.text('<');
                        next_button.text('>');
                    }

                    back_button.click(function(){
                        if(cur_page > 0){
                            cur_page--;
                            update();
                        }
                    });

                    next_button.click(function(){
                        if( cur_page < (pages - 1))
                        {
                            cur_page++
                            update();
                        }
                    });

                    update();

                    function update(){

                        max_page_counter.text(pages);
                        cur_page_counter.text(cur_page + 1);
                        var cur_index = max_number_per_page * cur_page;

                        child_elements.hide();
                        for( i = cur_index; i < ((cur_page + 1)* max_number_per_page ); i++ )
                        {
                            $(child_elements[i]).show();
                        }
                    }
                });
            </script>
        </div>
            <?php
            endif;
        if(isset($this->story)):

            foreach($this->story as $story)
            {
                ?>
                <div class="col-16 no-pad">
                    <div class="gray_box">
                        <h2 class="story-title white_box"><?=$story['title'] ?></h2>
                        <div class="message_info_box">
                            <a href="<?=$this->url(array(
                                'controller' => 'story',
                                'action' => 'index',
                                'id'    => null)) ?>">Terug naar overzicht</a>
                        </div>
                        <div class="col-10">
                            <div class="white_box">
                            <h4>Introductie</h4>
                                <p><?=$story['introduction'] ?></p>
                                <h4>Uitdaging</h4>
                                <p><?=$story['challenges'] ?></p>
                                <h4>Conclusie</h4>
                                <p><?=$story['conclusion'] ?></p>
                            </div>
                        </div>
                        <div class="col-6 no-pad">
                            <div class="white_box">
                                <h4>Competenties</h4>
                                <ul class="competentie_list">
                                    <?php
                                    foreach($this->story_comp as $comp)
                                    {
                                        ?>
                                        <li>
                                            <?=$comp['name']?> -
                                            <span class="blue">
                                                <?=$comp['type'] ?>
                                            </span>
                                        </li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                                <h4>Skills</h4>
                                <ul class="skill_list">
                                    <?php

                                    foreach($this->story_skill as $skill){

                                        ?>
                                        <li><a href="<?= $this->url(array('controller' => 'skill', 'action' => 'index', 'id' => $skill->get_id())) ?>"><?= $skill->get_skill_name()?></a></li>
                                    <?php
                                    }

                                    ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-16 comment-section">
                    <div class="gray_box">
                        <div class="white_box">
                            <h4>Commentaar</h4>
                        </div>
                        <div class="comment-container">
                            <?php foreach($this->comments as $comment): ?>
                                <div class="comment">
                                    <span class="left comment-name"> <?= $comment->get_user() ?></span>
                                    <span class="right blue comment-date"><?= date("j M G:i", strtotime($comment->get_time_stamp())) ?></span>
                                    <p class="comment-text"> <?= $comment->get_comment() ?></p>

                                </div>
                            <?php endforeach; ?>
                            <?php if(count($this->comments) < 1): ?>
                                <p>Geen commentaar</p>
                            <?php endif; ?>
                        </div>

                        <div class="comment-form">
                            <form action="<?=$this->url(array('controller' => 'comment', 'action' => 'index')) ?>" method="post" class="">
                                <input name="comment_user" type="hidden" value="<?=Auth_AuthChecker::getInstance()->getId() ?>">
                                <input name="comment_story_id" type="hidden" value="<?=$story['id'] ?>">
                                <textarea class="comment-textarea" name="comment_content" placeholder="Vul hier u commentaar in."></textarea>
                                <input type="submit" value="Toevoegen" class="main-btn comment_save_button">
                            </form>
                        </div>
                    <script>
                        //send form info to right url
                        $('.comment-form > form').submit(function(e){
                            e.preventDefault();

                            var form = $(this);
                            var form_raw_data = form;
                            var form_data = form.serialize();
                            var form_action = form.attr('action');

                            $.ajax({
                                url: form_action,
                                type: 'POST',
                                data: form_data,
                                success: function(response)
                                {
                                    console.log('succes');
                                    updateCommentSection(form_raw_data);
                                },
                                error: function(xhr)
                                {
                                    console.log(xhr);
                                }
                            })

                        });

                        function updateCommentSection(comment_data){
                            var story_id = <?=Zend_Controller_Front::getInstance()->getRequest()->getParam('id'); ?>;
                            location.reload(true);
                        }

                    </script>
                    </div>
                </div>

                <?
            }
        endif;
        ?>

    </div>
