<?php
/**
 * Created by PhpStorm.
 * User: stijn
 * Date: 19-4-2016
 * Time: 12:50
 */

$challenges = $this->challenges;
$user_array_challenge = $this->user_challenges;

?>
<div class="main_section">
    <h1 class="main_title align_left">Nieuwe uitdagingen</h1>
    <ul class="basic_list">
        <li>
            <?php
            $counter = 1;
            foreach($challenges as $challenge):
            ?>
                <span>#<?=$counter ?></span>
                <div class="challenge">
                    <div class="challenge_description">
                        <div>
                            <h3><?=$challenge['name'] ?></h3>
                            <a data-id = "<?=$challenge['id'] ?>" class="add_challenge <?= (in_array($challenge['id'], $user_array_challenge)) ? 'accepted' : '' ?>">
                                <?= (in_array($challenge['id'], $user_array_challenge)) ? 'Geaccepteerd' : 'Accepteer' ?>
                            </a>
                        </div>
                        <p><?=$challenge['description'] ?></p>

                    </div>
                    <div class="challenge_details">
                        <ul class="challenge_list">
                            <li>Training: <span><?=$challenge['type_of_training'] ?></span></li>
                            <li>Type: <span><?=$challenge['type'] ?></span></li>
                            <li>Doel: <span><?=$challenge['goal'] ?></span></li>
                            <li>Punten: <span><?=$challenge['value'] ?></span></li>
                        </ul>
                    </div>
                </div>
            <?php
            $counter++;
            endforeach;
            ?>



</div>
<script>
    var accept_buttons = $('.add_challenge');
    accept_buttons.click(function(e){
        var item = $(this);
        var id = item.attr('data-id');
        console.log(id);
        addChallenge(id, item);
        e.preventDefault();
    });


    function addChallenge(challenge_id, item)
    {
        $.post( "<?= $this->url(array(  'controller' => 'ajax',
            'action' => 'addchallenge'))?>", "challenge_id="+challenge_id, function( data ) {

            item.addClass('accepted');
            item.text('Geaccepteerd');
        });
    }

</script>
