<?php
/**
 * Created by PhpStorm.
 * User: stijn
 * Date: 19-4-2016
 * Time: 12:50
 */

$stats_model = $this->user_stats_model;
$user_model = $this->user_model;
?>
<div class="main_section">
    <h1 class="main_title align_left">
        Mijn statistieken
    </h1>
    <h2 class="sub_title">Basics</h2>
    <ul class="basic_list">
        <li>Fitheid level: <span><?=$user_model->getFitLevel() ?></span></li>
        <li>Cardio punten: <span><?=$user_model->getCardioPoints() ?></span></li>
        <li>Kracht punten: <span><?=$user_model->getKrachtPoints() ?></span></li>
        <li>Uitdagingen aangeggaan: <span><?= (int)$stats_model->getAmountAllChallenges(false) + (int)$stats_model->getAmountAllChallenges(true) ?></span></li>
        <li>Uitdagingen behaald: <span><?=(int)$stats_model->getAmountAllChallenges(true) ?></span></li>
    </ul>
    <h2 class="sub_title">Conditie training</h2>
    <ul class="basic_list">
        <li>Totale afstand: <span>12101 km</span></li>
        <li>Totale tijd: <span>3 dagen 20 uur en 10 minuten</span></li>
    </ul>
    <h2 class="sub_title">Kracht training</h2>
    <ul class="basic_list">
        <li>Total aantal herhalingen: <span>123151</span></li>
        <li>Totale gewicht: <span>23415234 kg</span></li>
        <li>Favoritie spiergroep <span>Borst</span></li>
        <li>Minst favorietie spiergroep <span>Buik</span></li>
    </ul>
</div>
