<?php
/**
 * Created by PhpStorm.
 * User: stijn
 * Date: 19-4-2016
 * Time: 12:50
 */

?>
<div class="main_section">
    <h1 class="main_title align_left">
        Mijn statistieken
    </h1>
    <h2 class="sub_title">Basics</h2>
    <ul class="basic_list">
        <li>Fitheid level: <span>20</span></li>
        <li>Cardio punten: <span>1234</span></li>
        <li>Kracht punten: <span>1234</span></li>
        <li>Uitdagingen aangeggaan: <span>34</span></li>
        <li>Uitdagingen behaald: <span>12</span></li>
    </ul>
    <h2 class="sub_title">Cardio</h2>
    <ul class="basic_list">
        <li>Totale afstand: <span>12101 km</span></li>
        <li>Totale tijd: <span>3 dagen 20 uur en 10 minuten</span></li>
    </ul>
    <h2 class="sub_title">Kracht</h2>
    <ul class="basic_list">
        <li>Total aantal herhalingen: <span>123151</span></li>
        <li>Totale gewicht: <span>23415234 kg</span></li>
        <li>Favoritie spiergroep <span>Borst</span></li>
        <li>Minst favorietie spiergroep <span>Buik</span></li>
    </ul>
</div>
