<?php
/**
 * Created by PhpStorm.
 * User: stijn
 * Date: 13-4-2016
 * Time: 16:05
 */

?>

<div class="main_section">
    <h1 class="main_title">
        Beginner training
    </h1>
    <h2 class="train_day">
        dag 2
    </h2>
</div>
<div class="training_message final_message">
    <h1 class="title">Training afgerond!</h1>
    <h2 class="sub_title">+100 pts.</h2>
    <button class="main_button">Oke</button>
</div>
<div class="box_slider">
<?php
$counter = 0;
foreach($this->oefeningen as $oefening):
?>
    <div class="training_container">
        <div class="training_description">
            <img class="icon_back" src="<?=$this->baseUrl('img/icons/back_arrow_icon2.png') ?>" alt="terug" >
            <h2 class="title"><?=$oefening['name'] ?></h2>
            <h3 class="sub_title align_center"><?=$oefening['type'] ?></h3>
            <img class="icon_next" src="<?=$this->baseUrl('img/icons/next_arrow_icon2.png') ?>" alt="volgende" >
        </div>
        <?php
            if($this->training_type == 'kracht'):
        ?>

        <!--if type = kracht-->
                <p class="instruction">
                    <span><?=$oefening['reps'] ?></span> herhalingen voor <span><?=$oefening['sets'] ?></span> sets.
                </p>

                <form class="basic_form" method="post" action="">
                    <input type="hidden" value="<?=$oefening['id'] ?>" name="oefening_id">
                    <input type="hidden" value="<?=$oefening['type'] ?>" name="oefening_type">
                    <input type="hidden" value="<?=$this->training_type ?>" name="training_type">
                    <?php
                    $amount_of_sets = $oefening['sets'];

                    for ($x = 1; $x <= $amount_of_sets; $x++) {
                        ?>
                        <label>
                            set <?=$x ?>:
                            <!--<input type="number" name="set<?/*=$x*/?>">-->
                            <input type="number" name="sets[]">
                        </label>

                        <?php
                    }
                    ?>
                    <input type="submit" value="Opslaan" class="main_button">
                </form>



        <?php
                endif;
            if($this->training_type == 'cardio'):


                if($oefening['type'] == 'afstand')
                {
        ?>
                    <p class="instruction">
                        <span><?=$oefening['name']?></span> voor <span><?=$oefening['distance'] ?></span> meter.
                    </p>
                    <form class="basic_form" method="post" action="">
                        <input type="hidden" value="<?=$oefening['id'] ?>" name="oefening_id">
                        <input type="hidden" value="<?=$oefening['type'] ?>" name="oefening_type">
                        <input type="hidden" value="<?=$this->training_type ?>" name="training_type">
                        <input type="hidden" value="0" name="time_seconds" class="time_input_field_<?=$oefening['id'] ?>">
                       <!-- <label>
                            Minuten:
                            <input type="number" name="time" />
                        </label>-->

                        <span class="timer timer_<?=$oefening['id'] ?>"><span class="minutes_<?=$oefening['id'] ?>">0</span>:<span class="seconds_<?=$oefening['id'] ?>">00</span></span>
                        <button class="start_timer_btn start_timer_btn_<?=$oefening['id'] ?> main_button">Start timer</button>

                        <input type="hidden" value="<?=$oefening['distance'] ?>" name="distance">
                        <?php


                        ?>
                        <input type="submit" value="Opslaan" class="main_button exercise_<?=$oefening['id'] ?>_submit">
                        <script>
                            var active = false;

                            $('.exercise_<?=$oefening['id'] ?>_submit').hide();
                            $('.start_timer_btn_<?=$oefening['id'] ?>').click(function(e){

                                if(!active) {
                                    active = true;
                                }

                                var timer = $('.timer_<?=$oefening['id'] ?>');
                                var minutes = $('.minutes_<?=$oefening['id'] ?>');
                                var seconds = $('.seconds_<?=$oefening['id'] ?>');
                                var input = $('.time_input_field_<?=$oefening['id'] ?>');

                                var total_seconds = 0;
                                var cur_seconds = 0;
                                var cur_min = 0;

                                $(this).text('Stop timer');

                                $('.start_timer_btn_<?=$oefening['id'] ?>').click(function(e){
                                    active = false;
                                    input.val(total_seconds);
                                    $(this).remove();
                                    $('.exercise_<?=$oefening['id'] ?>_submit').show();
                                });


                                setInterval(function() {

                                    if(active) {
                                        if (cur_seconds == 59) {
                                            cur_min++;
                                            cur_seconds = 0;
                                        }
                                        else {
                                            cur_seconds++;
                                        }

                                        seconds.text(('0' + cur_seconds).slice(-2));
                                        minutes.text(cur_min);

                                        total_seconds++;
                                    }

                                }, 1000);

                                e.preventDefault();
                            });

                        </script>
                    </form>
        <?php
                }
                if($oefening['type'] == 'tijd')
                {
        ?>
                    <p class="instruction">
                        <span><?=$oefening['name'] ?></span> voor <span><?=$oefening['time'] ?></span> minu(u)t(en).
                    </p>
                    <form class="basic_form" method="post" action="">
                        <input type="hidden" value="<?=$oefening['id'] ?>" name="oefening_id">
                        <input type="hidden" value="<?=$oefening['type'] ?>" name="oefening_type">
                        <input type="hidden" value="<?=$this->training_type ?>" name="training_type">
                        <label class="distance_input_<?=$oefening['id'] ?>">
                            Meters:
                            <input type="number" name="distance" />
                        </label>
                        <input type="hidden" value="<?=$oefening['time'] * 60 ?>" name="time_seconds">

                        <span class="timer timer_<?=$oefening['id'] ?>"><span class="minutes_<?=$oefening['id'] ?>"><?=(int)$oefening['time'] ?></span>:<span class="seconds_<?=$oefening['id'] ?>">00</span></span>
                        <button class="start_timer_btn start_timer_btn_<?=$oefening['id'] ?> main_button">Start oefening</button>

                        <input type="submit" value="Opslaan" class="main_button exercise_<?=$oefening['id'] ?>_submit">
                        <script>
                            var active = false;

                            $('.exercise_<?=$oefening['id'] ?>_submit').hide();
                            $('.distance_input_<?=$oefening['id'] ?>').hide();


                            $('.start_timer_btn_<?=$oefening['id'] ?>').click(function(e){

                                console.log(active);

                                if(!active) {
                                    active = true;
                                }

                                var timer = $('.timer_<?=$oefening['id'] ?>');
                                var minutes = $('.minutes_<?=$oefening['id'] ?>');
                                var seconds = $('.seconds_<?=$oefening['id'] ?>');

                                var total_seconds = <?=(int)$oefening['time'] * 60 ?>;
                                var cur_seconds = 0;
                                var cur_min = <?=(int)$oefening['time'] ?>;

                                $(this).hide();

                                setInterval(function() {

                                    if(total_seconds <= 0)
                                    {
                                        active = false;
                                        $(this).remove();
                                        $('.exercise_<?=$oefening['id'] ?>_submit').show();
                                        $('.distance_input_<?=$oefening['id'] ?>').show();

                                    }

                                    if(active) {

                                        console.log('value');

                                        if (cur_seconds == 0) {
                                            cur_min--;
                                            cur_seconds = 59;
                                        }
                                        else {
                                            cur_seconds--;
                                        }

                                        seconds.text(('0' + cur_seconds).slice(-2));
                                        minutes.text(cur_min);

                                        total_seconds--;
                                    }

                                }, 1000);

                                e.preventDefault();
                            });

                        </script>

                    </form>
        <?php
                }
                ?>

        <!--if type = cardio-->

        <?php
            endif;
        ?>
    </div>


<?php
$counter++;
endforeach;
?>
</div>

<script>
    /*this script is used to slide trough the different excercises*/


    var slider_box = $('.box_slider');
    var items = slider_box.find( $('.training_container'));
    var final_message = $('.final_message');
    var cur_item = 0;
    final_message.hide();

    start();

    function init(){
        console.log('initialize stuff');

        slider_box = $('.box_slider');
        items = slider_box.find( $('.training_container'));
        cur_item = 0;

        console.log(items.length);

        if(items.length >= 1)
        {

            if(items.length == 1)
            {
                console.log('hide arrows');
                start();
                hide_arrows();
            }
            else{
                start();
            }

        }
        else {
            final_message.show();
        }


    }

    function start(){

        console.log('start stuff');
        items.hide();
        $(items[cur_item]).show();

        if(items.length == 1)
        {
            hide_arrows();
        }
    }

    function back_action(){
        if(cur_item > 0){
            cur_item--;
        }
        else {
            cur_item = (items.length - 1)
        }

        start();
    }

    function next_action(){
        if(cur_item < (items.length - 1))
        {
            cur_item++
        }
        else {
            cur_item = 0;
        }

        start();
    }

    /*action*/
    var next_button = $('.icon_next');
    var back_button = $('.icon_back');

    next_button.click(function(e){
       next_action();
    });
    back_button.click(function(e){
       back_action();
    });

    function hide_arrows(){

        next_button = $('.icon_next');
        back_button = $('.icon_back');

        next_button.hide();
        back_button.hide();
    }
    function show_arrows(){
        next_button.show();
        back_button.show();
    }



    /*finsihed message is clicked*/

    final_message.find('button').click(function(e){

        $.post( "<?= $this->url(array(  'controller' => 'ajax',
            'action' => 'completetraining'))?>", 'finished', function( return_data ) {

            /*this works !!!*/
            window.location.href = '<?=$this->url(array(  'controller' => 'index',
            'action' => 'index')) ?> ';
        })

        e.preventDefault();
    });

</script>
<script>
    $("form").submit(function(e){


        var form = $(this);
        var data = form.serialize();
        console.log(data);

        /*post to the right location*/
        $.post( "<?= $this->url(array(  'controller' => 'ajax',
            'action' => 'completeexercise'))?>", data, function( return_data ) {

            /*remove finished training from the list*/
            form.parent(".training_container").remove();

            /*go to next exercise*/
            init();
        })

        e.preventDefault();
    });

</script>


