<?php
/**
 * Created by PhpStorm.
 * User: stijn
 * Date: 13-4-2016
 * Time: 09:48
 */

$type_of_training = $this->training_type;
$training_id = $this->training_id;
$training_days = $this->training_days;
?>

<div class="main_section">
    <h1 class="main_title">Oefeningen toevoegen</h1>
    <h2 class="sub_title"><?=$type_of_training ?></h2>
</div>

<?php
if($type_of_training == "cardio"):
?>
<!--do form with ajax call if i have the time-->
<form class="basic_form active_form" method="post" >
    <input type="hidden" value="cardio" name="type_of_training">
    <input type="hidden" value="<?=$this->training_id ?>" name="training_id">
    <label>
        <span>Naam:</span><input type="text" placeholder="Bijv. hardlopen, roeien" name="name">
    </label>
    <label>
        <span>Dag:</span>
        <select name="day" class="training_type">

            <?php
            for ($x = 1; $x <= $training_days; $x++) {
                ?>
                <option value="<?=$x?>"><?=$x ?></option>

                <?php
            }

            ?>
        </select>
    </label>
    <label>
        <span>Type:</span>
        <select name="type" class="training_type">
            <option value="afstand">Afstand</option>
            <option value="tijd">Tijd</option>
        </select>
    </label>
    <label class="afstand">
        <span>Afstand (meter):</span><input type="number" value="0" name="distance">
    </label>
    <label class="tijd">
        <span>Tijd (minuten):</span><input type="number" value="0" name="time">
    </label>
    <?php
    if($this->message != null){
        ?>
        <div class="message_warning_box">
            <?=$this->message ?>
        </div>
        <?php
    }
    ?>
    <div class="">
        <input type="submit" value="Toevoegen" class="main_button form_btn">
    </div>
</form>
    <div class="main_section newsection">
        <h1 class="main_title">Overzicht</h1>

        <!--foreacht to add list and title-->
        <h2 class="sub_title left">Afstand</h2>
        <ul class="basic_list" id="distance"></ul>
        <h2 class="sub_title left">Tijd</h2>
        <ul class="basic_list" id="time"></ul>

    </div>

    <script>
    /*use for switching form fields*/
    var afstand_form = $('.afstand');
    var tijd_form = $('.tijd');
    tijd_form.hide();
    afstand_form.show();


    $(".training_type").change(function(e){

        var value = $(this).val();
        console.log(value);

        if(value == 'afstand'){
            console.log('now its distance');
            afstand_form.show();
            tijd_form.hide();
        }
        if(value == 'tijd')
        {
            console.log('now its time');
            tijd_form.show();
            afstand_form.hide();
        }
    });

</script>




<?php
/*Dit deel is verantwoordelijk voor krachttraining only!!!*/
endif;
if($type_of_training == 'kracht'):
?>
    <form class="basic_form active_form" method="post" >
        <input type="hidden" value="kracht" name="type_of_training">
        <input type="hidden" value="<?=$this->training_id ?>" name="training_id">
        <label>
            <span>Naam:</span><input type="text" placeholder="" name="name">
        </label>
        <label>
            <span>Dag:</span>
            <select name="day" class="training_type">

                <?php
                for ($x = 1; $x <= $training_days; $x++) {
                    ?>
                    <option value="<?=$x?>"><?=$x ?></option>

                    <?php
                }

                ?>
            </select>
        </label>
        <label>
            <span>Type:</span>
            <select name="type" class="training_type">
                <option value="benen">Benen & billen</option>
                <option value="borst">Borst</option>
                <option value="rug">Rug</option>
                <option value="schouders">Schouders</option>
                <option value="armen">Armen</option>
            </select>
        </label>
        <label class="">
            <span>Sets:</span><input type="number" value="0" name="sets" max="8">
        </label>
        <label class="">
            <span>Herhalingen:</span><input type="number" value="0" name="reps">
        </label>
        <?php
        if($this->message != null){
            ?>
            <div class="message_warning_box">
                <?=$this->message ?>
            </div>
            <?php
        }
        ?>
        <div class="">
            <input type="submit" value="Toevoegen" class="main_button form_btn">
        </div>

    </form>
    <div class="main_section newsection">
        <h1 class="main_title">Overzicht</h1>

        <!--foreacht to add list and title-->
        <h2 class="sub_title left">Benen & billen</h2>
        <ul class="basic_list" id="benen"></ul>
        <h2 class="sub_title left">Borst</h2>
        <ul class="basic_list" id="borst"></ul>
        <h2 class="sub_title left">Rug</h2>
        <ul class="basic_list rug" id="rug"></ul>
        <h2 class="sub_title left">Schouders</h2>
        <ul class="basic_list schouders" id="schouders"></ul>
        <h2 class="sub_title left">Armen</h2>
        <ul class="basic_list armen" id="armen"></ul>

    </div>
<?php
endif;


/*dit deel behoort to beide schermen*/
?>
<!--submit script-->
<script>
    $(".active_form").submit(function (e) {
        e.preventDefault();
        var data = $(this).serialize();
        console.log(data);

        $.post( "<?= $this->url(array(  'controller' => 'ajax',
            'action' => 'addexercise'))?>", data, function( data ) {
            console.log(data);

            var data = $.parseJSON(data);
            console.log(data);
            /*add list item to the right location*/

            /*cardio lists*/
            var afstand_list = $('#distance');
            var tijd_list = $('#time');

            /*kracht lists*/
            var benen_list = $('#benen');
            var borst_list = $('#borst');
            var rug_list = $('#rug');
            var schouder_list = $('#schouders');
            var arm_list = $('#armen');

            switch (data.type) {
                case 'afstand':
                    afstand_list.append(data.html);
                    update();
                    break;
                case 'tijd':
                    tijd_list.append(data.html);
                    update();
                    break;
                case 'benen':
                    benen_list.append(data.html);
                    update();
                    break;
                case 'borst':
                    borst_list.append(data.html);
                    update();
                    break;
                case 'rug':
                    rug_list.append(data.html);
                    update();
                    break;
                case 'schouders':
                    schouder_list.append(data.html);
                    update();
                    break;
                case 'armen':
                    arm_list.append(data.html);
                    update();
                    break;
            }
        });

        //clear form after submit: except button, submit, rest & hidden
        $(':input','.active_form')
            .not(':button, :submit, :reset, :hidden')
            .val('')
            .removeAttr('checked');
    });


</script>


<!--overview script-->
<script>
    function update(){
        change_list();
        remove_exericises();
        update_list();
    }

    function change_list(){
        var items = $('.item_selection');
        console.log('item_list is updated');
        items.hide();

        items.parent().click(function(e){
            console.log('item is clicked');
            $(this).toggleClass('active');
            $(this).children(".item_selection").slideToggle();
    });
    }

    function update_list(){

            $("ul").children( "span").remove();
            $("ul:empty").append("<span class='message'>Geen oefeningen</span>");

    }


    function remove_exericises(){
        var list = $('.remove');
        list.click(function (e) {

            e.preventDefault();
            var clicked_item = $(this);
            var id = clicked_item.attr('data-id');
            var item = clicked_item.closest('li');

            $.post( "<?= $this->url(array(  'controller' => 'ajax',
                'action' => 'removeexercise'))?>", "id="+id, function( data ) {
                item.remove();
                update();
                })
            });
        }


    update();
</script>


