<div class="main_section">
    <h1 class="main_title">Huidige training</h1>
<!--    <p class="sub_title">Mijn eerste training</p>
--> <div class="content_box_red">
        <h2 class="sub_title">Mijn eerst training</h2>
        <ul class="spec_list">
            <li>Aantal training's dagen: <span>1</span></li>
            <li>Huidige dag: <span>1</span></li>
            <li>Oefeningen: <span>0/12</span></li>
            <li>Progressie: <span>60%</span></li>
        </ul>
        <a href="#" class="main_button">Start training</a>
    </div>
    <!--<div class="more-arrow"></div>-->

</div>
<div class="selection_container">
    <ul>
        <li><a href="#" class="formlink">Statistieken</a></li>
        <li><a href="#" class="formlink">Training toevoegen</a></li>
        <li><a href="#" class="formlink">Training selecteren</a></li>
    </ul>
</div>