<div class="main_section">
    <h1 class="main_title">Training selecteren</h1>
</div>
<h2 class="sub_title left">Afgerond</h2>
<ul class="basic_list">
    <?php
    $completed_counter = 0;
    foreach($this->trainingen as $training)
    {
        if($training['completed'] == 1):
            ?>

        <li data-id = "<?=$training['id'] ?>" class="train_item completed_item">

            <span>
                    <?=$training['name'] ?>
                </span>
            <div class="item_selection">
                <a href="" class="">Statistieken</a>
                <a href="" class="">Verwijderen</a>
            </div>
        </li>

    <?php
        $completed_counter++;
        endif;
    }

    if($completed_counter < 1)
    {
        ?>
        <li><span>Geen trainingen gevonden.</span></li>
        <?php
    }

    ?>

</ul>
<h2 class="sub_title left">Bezig</h2>
<ul class="basic_list">

    <?php

    $busy_counter = 0;
    foreach($this->trainingen as $training)
    {
        if($training['completed'] == 0):
            ?>

            <li data-id = "<?=$training['id'] ?>" class="train_item working_item">

                <span>
                    <?=$training['name'] ?>
                </span>
                <div class="item_selection">
                    <a class="select_training">Selecteren</a>
                    <a class="training_stats">Statistieken</a>
                    <a class="remove_training">Verwijderen</a>
                </div>


            </li>
            <?php
            $busy_counter++;
        endif;
    }

    if($busy_counter < 1)
    {
        ?>
        <li><span>Geen trainingen gevonden.</span></li>
    <?php
    }

    ?>

</ul>

<script>

    var items = $('.item_selection');

    items.hide();

    items.parent().click(function(e){
        console.log('item is clicked');
        $(this).toggleClass('active');
        $(this).children(".item_selection").slideToggle();
    });

    var select_buttons = $('.select_training');
    var remove_buttons = $('.remove_training');

    select_buttons.click(function(e){
        var clicked_item = ($(this));
        var parent_item = $(this).parents('li');
        var id = ($(parent_item).attr('data-id'));
        selectTraining(id);
        e.preventDefault();
    });

    remove_buttons.click(function(e){
        var clicked_item = ($(this));
        var parent_item = $(this).parents('li');
        var id = ($(parent_item).attr('data-id'));
        removeTraining(id);
        parent_item.remove();
        e.preventDefault();
    });

    function selectTraining(id){

        /*do post*/
        $.post( "<?= $this->url(array(  'controller' => 'ajax',
            'action' => 'setcurtraining'))?>", "id="+id, function( data )
        {

            console.log('training selected');
            window.location.href = "<?=$this->url(array(  'controller' => 'training',
                'action' => 'index')) ?>";

        });

    }
    function removeTraining(id)
    {
        alert('Weet je zeker dat je deze training wilt verwijderen?');
        /*do post*/
        $.post( "<?= $this->url(array(  'controller' => 'ajax',
            'action' => 'removetraining'))?>", "id="+id, function( data )
        {
            console.log('training removed');
        });
    }


</script>